version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: tiktaktoe
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - local_network

volumes:
  mysql_data:

networks:
  local_network:
