logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tiktaktoe
    username: root
    password: rootPassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration